/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifsul.cc.lpoo.cv.gui.Funcionario;

import br.edu.ifsul.cc.lpoo.cv.Controle;
import br.edu.ifsul.cc.lpoo.cv.model.Funcionario;

/**
 *
 * @author bianca.evangelista
 */
public class JPanelEdicao extends javax.swing.JPanel {

    private JPanelFuncionario pnlFuncionario;
    private Controle controle; 
    
    public JPanelEdicao(JPanelFuncionario pnlFuncionario,Controle controle) {
        this.pnlFuncionario = pnlFuncionario;
        this.controle = controle;
        initComponents();
    }

    public Funcionario getFormulario(){
        //validação para user novo
        
        if(txfCPF.getText().trim().length() == 11 && txfNome.getText().trim().length() > 0){
            Funcionario fun = new Funcionario();
            fun.setCpf(txfCPF.getText().trim());
            fun.setNome(txfNome.getText().trim());
            fun.setNumero_ctps(txfNumeroCTPS.getText().trim());
            fun.setNumero_pis(txfNumeroPIS.getText().trim());
            
            return fun;
        }
        return null;
    }
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlSul = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        pnlCentro = new javax.swing.JPanel();
        lblCPF = new javax.swing.JLabel();
        txfCPF = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        txfNome = new javax.swing.JTextField();
        lblNumeroCTPS = new javax.swing.JLabel();
        txfNumeroCTPS = new javax.swing.JTextField();
        lblNumeroPIS = new javax.swing.JLabel();
        txfNumeroPIS = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        pnlSul.add(btnSalvar);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlSul.add(btnCancelar);

        add(pnlSul, java.awt.BorderLayout.PAGE_END);

        pnlCentro.setLayout(new java.awt.GridBagLayout());

        lblCPF.setText("CPF:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pnlCentro.add(lblCPF, gridBagConstraints);

        txfCPF.setColumns(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlCentro.add(txfCPF, gridBagConstraints);

        lblNome.setText("Nome: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pnlCentro.add(lblNome, gridBagConstraints);

        txfNome.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlCentro.add(txfNome, gridBagConstraints);

        lblNumeroCTPS.setText("Numero CTPS:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pnlCentro.add(lblNumeroCTPS, gridBagConstraints);

        txfNumeroCTPS.setColumns(20);
        txfNumeroCTPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfNumeroCTPSActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlCentro.add(txfNumeroCTPS, gridBagConstraints);

        lblNumeroPIS.setText("Numero PIS: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pnlCentro.add(lblNumeroPIS, gridBagConstraints);

        txfNumeroPIS.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlCentro.add(txfNumeroPIS, gridBagConstraints);

        add(pnlCentro, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txfNumeroCTPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfNumeroCTPSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfNumeroCTPSActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        pnlFuncionario.showTela("tela_listagem");

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        pnlFuncionario.showTela("tela_listagem");
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumeroCTPS;
    private javax.swing.JLabel lblNumeroPIS;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlSul;
    private javax.swing.JTextField txfCPF;
    private javax.swing.JTextField txfNome;
    private javax.swing.JTextField txfNumeroCTPS;
    private javax.swing.JTextField txfNumeroPIS;
    // End of variables declaration//GEN-END:variables
}
