/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifsul.cc.lpoo.cv.gui.Venda;

import br.edu.ifsul.cc.lpoo.cv.Controle;
import br.edu.ifsul.cc.lpoo.cv.model.Venda;
import java.awt.event.ActionEvent;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author bianca.evangelista
 */
public class JPanelEdicaoV extends javax.swing.JPanel {

    private JPanelVenda pnlVenda;
    private Controle controle;

    public JPanelEdicaoV(JPanelVenda pnlFuncionario, Controle controle) {
        this.pnlVenda = pnlFuncionario;
        this.controle = controle;
        initComponents();
    }

    public Venda getFormulario() {
        //validação para user novo

        if (txfObs.getText().trim().length() > 0 && txfVlrTotal.getText().trim().length() > 0) {
            Venda fun = new Venda();
            // fun.setId(txfId.get().trim());
            fun.setObservacao(txfObs.getText().trim());
            //fun.setPagamento(txfPagamento.getText().trim());
            float num = new Float(txfVlrTotal.getText());
            //fun.setValor_total(txfVlrTotal.getText().trim());
            //fun.setData(txfData.getText());

            return fun;
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlSul = new javax.swing.JPanel();
        btnSalvarV = new javax.swing.JToggleButton();
        bntCancelarV = new javax.swing.JToggleButton();
        pnlCentro = new javax.swing.JPanel();
        lblObs = new javax.swing.JLabel();
        txfObs = new javax.swing.JTextField();
        lblVlrTotal = new javax.swing.JLabel();
        txfVlrTotal = new javax.swing.JTextField();
        lblData = new javax.swing.JLabel();
        txfData = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        btnSalvarV.setText("Salvar Venda");
        btnSalvarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarVActionPerformed(evt);
            }
        });
        pnlSul.add(btnSalvarV);

        bntCancelarV.setText("Cancelar Venda");
        bntCancelarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCancelarVActionPerformed(evt);
            }
        });
        pnlSul.add(bntCancelarV);

        add(pnlSul, java.awt.BorderLayout.PAGE_END);

        pnlCentro.setLayout(new java.awt.GridBagLayout());

        lblObs.setText("Observação: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pnlCentro.add(lblObs, gridBagConstraints);

        txfObs.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlCentro.add(txfObs, gridBagConstraints);

        lblVlrTotal.setText("Valor Total: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pnlCentro.add(lblVlrTotal, gridBagConstraints);

        txfVlrTotal.setColumns(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlCentro.add(txfVlrTotal, gridBagConstraints);

        lblData.setText("Data: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        pnlCentro.add(lblData, gridBagConstraints);

        txfData.setColumns(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlCentro.add(txfData, gridBagConstraints);

        add(pnlCentro, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarVActionPerformed
        Venda v = getFormulario();
        if (v != null) {

            try {
                v.setId(WIDTH);
                v.setData(Calendar.getInstance());
                pnlVenda.getControle().getConexaoJDBC().persist(v);
                JOptionPane.showMessageDialog(this, "Venda Salva!", "Salvar", JOptionPane.INFORMATION_MESSAGE);
                
                pnlVenda.showTela("tela_listagem");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Erro ao salvar!", "Salvar", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }

        }
        pnlVenda.showTela("tela_listagem");

    }//GEN-LAST:event_btnSalvarVActionPerformed

    private void bntCancelarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCancelarVActionPerformed
        pnlVenda.showTela("tela_listagem");
    }//GEN-LAST:event_bntCancelarVActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton bntCancelarV;
    private javax.swing.JToggleButton btnSalvarV;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblObs;
    private javax.swing.JLabel lblVlrTotal;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlSul;
    private javax.swing.JTextField txfData;
    private javax.swing.JTextField txfObs;
    private javax.swing.JTextField txfVlrTotal;
    // End of variables declaration//GEN-END:variables
}
