/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifsul.cc.lpoo.cv.gui.Venda;

import br.edu.ifsul.cc.lpoo.cv.Controle;
import br.edu.ifsul.cc.lpoo.cv.model.Venda;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bianca.evangelista
 */
public class JPanelListagemV extends javax.swing.JPanel {

    private JPanelVenda pnlVenda;
    private Controle controle;

    public JPanelListagemV(JPanelVenda pnlVenda, Controle controle) {
        this.pnlVenda = pnlVenda;
        this.controle = controle;
        initComponents();
    }

    public void populaTable() {

        DefaultTableModel model = (DefaultTableModel) tblListagem.getModel();//recuperacao do modelo da tabela

        model.setRowCount(0);//elimina as linhas existentes

       try {
        	SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");  
            List<Venda> listV = controle.getConexaoJDBC().listVendas();
            for (Venda v : listV) {
            	Calendar cal = v.getData();
            	Date data = cal.getTime();
                
                model.addRow(new Object[]{v.getId(), v.getObservacao(), v.getValor_total(), formatter.format(data), v.getPagamento(), v.getConsultas()});
            }

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(this, "Erro ao listar Vendas -:" + ex.getLocalizedMessage(), "Vendas", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSul = new javax.swing.JPanel();
        btnNovoV = new javax.swing.JToggleButton();
        btnEditarV = new javax.swing.JToggleButton();
        btnRemoverV = new javax.swing.JToggleButton();
        pnlNorte = new javax.swing.JPanel();
        lblFiltroId = new javax.swing.JLabel();
        txfFiltroId = new javax.swing.JTextField();
        btnFiltrarV = new javax.swing.JToggleButton();
        pnlCentro = new javax.swing.JPanel();
        scpRolagem = new javax.swing.JScrollPane();
        tblListagem = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        btnNovoV.setText("Nova Venda");
        btnNovoV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoVActionPerformed(evt);
            }
        });
        pnlSul.add(btnNovoV);

        btnEditarV.setText("Editar Venda");
        btnEditarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarVActionPerformed(evt);
            }
        });
        pnlSul.add(btnEditarV);

        btnRemoverV.setText("Remover Venda");
        pnlSul.add(btnRemoverV);

        add(pnlSul, java.awt.BorderLayout.PAGE_END);

        lblFiltroId.setText("Filtrar Venda:");
        pnlNorte.add(lblFiltroId);

        txfFiltroId.setColumns(20);
        pnlNorte.add(txfFiltroId);

        btnFiltrarV.setText("Filtrar Venda");
        btnFiltrarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarVActionPerformed(evt);
            }
        });
        pnlNorte.add(btnFiltrarV);

        add(pnlNorte, java.awt.BorderLayout.PAGE_START);

        pnlCentro.setLayout(new java.awt.BorderLayout());

        tblListagem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Observação", "Valor Total", "Data", "Pagamento", "ID Consulta"
            }
        ));
        scpRolagem.setViewportView(tblListagem);

        pnlCentro.add(scpRolagem, java.awt.BorderLayout.CENTER);

        add(pnlCentro, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFiltrarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFiltrarVActionPerformed

    private void btnNovoVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoVActionPerformed
        pnlVenda.showTela("tela_edicao");

// TODO add your handling code here:
    }//GEN-LAST:event_btnNovoVActionPerformed

    private void btnEditarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarVActionPerformed
        pnlVenda.showTela("tela_edicao");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarVActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnEditarV;
    private javax.swing.JToggleButton btnFiltrarV;
    private javax.swing.JToggleButton btnNovoV;
    private javax.swing.JToggleButton btnRemoverV;
    private javax.swing.JLabel lblFiltroId;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlNorte;
    private javax.swing.JPanel pnlSul;
    private javax.swing.JScrollPane scpRolagem;
    private javax.swing.JTable tblListagem;
    private javax.swing.JTextField txfFiltroId;
    // End of variables declaration//GEN-END:variables
}
